packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@types/node': 24.9.2
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  'next': 16.0.1
  'eslint-config-next': 16.0.1
  '@next/eslint-plugin-next': 16.0.1
  '@next/bundle-analyzer': 16.0.1
  'supabase': 2.54.11
  'tailwindcss': 4.1.16
  '@tailwindcss/postcss': 4.1.16
  'tw-animate-css': 1.4.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
